-- 코드를 입력하세요
SELECT O.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE,'YYYY-MM') = '2022-05'
GROUP BY O.PRODUCT_ID,PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID