-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT,date_format(REVIEW_DATE,'%Y-%m-%d')
from MEMBER_PROFILE m
join REST_REVIEW r
on m.MEMBER_ID = r.MEMBER_ID
where r.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_SCORE) DESC
    limit 1
)
order by REVIEW_DATE,REVIEW_TEXT