-- 코드를 입력하세요
-- SELECT MEMBER_NAME,REVIEW_TEXT,REVIEW_DATE
-- FROM MEMBER_PROFILE M
-- JOIN REST_REVIEW R
-- ON M.MEMBER_ID = R.MEMBER_ID

-- ORDER BY REVIEW_DATE,REVIEW_TEXT

SELECT MEMBER_NAME,REVIEW_TEXT,TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID
IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        FETCH FIRST 1 ROWS ONLY
    )
)
ORDER BY REVIEW_DATE,REVIEW_TEXT

